### ISSUE TITLE
U MNIE NIE DZIAŁA !!

### ISSUE THREAD

**Issue by wojtazk** [gegangene/succert#1]
Pls fix :+1:

**Comment by gegangene** [comment]
panie, jak działa na produkcji znaczy że działa, jesteśmy poważnymi studentami xD
(tak serio to app/.venv się nie da do repo dodać bo dotdirectories nie wchodzą więc trzeba dockerfile przepisać ale nikt już nie miał na to ochoty po 23h pieprzenia się z kontenerami :>)
